model: EASE
data_path: /data/ephemeral/home/code/dataset/
dataset: my_dataset

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: time

reg_weight: 500.0
train_batch_size: 8192
eval_batch_size: 8192
worker: 6
epochs: 1

train_neg_sample_args: null

eval_args:
    split: {'RS': [1.0,0.0,0.0]}
    order: RO
    group_by: user
    mode: full

metrics: ['Recall', 'NDCG', 'MRR', 'Hit']
topk: 10
valid_metric: Recall@10

log_wandb: True
wandb_project: 'EASE_Project'
device: cuda